spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
    datasource:
      url: ${DATASOURCE_URL}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PW}
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  secret-key: ${JWT_SECRET}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

  naver:
     client-id: ${NAVER_CLIENT_ID}
     secret: ${NAVER_CLIENT_SECRET}
     url:
       auth: https://nid.naver.com/
       api: https://openapi.naver.com/